### ISSUE TITLE
HMR broken since 5.0.0

### ISSUE THREAD

**Issue by dsgkirkby** [reactjs/react-redux#619]
Since updating to 5.0.x, my app's connected components stop updating after the app is hot reloaded. This issue is resolved when I downgrade back to 4.4.6.

A (reasonably) minimal repro can be found here: https://github.com/dsgkirkby/react-redux-hmr-bug.

**Comment by timdorr** [comment]
Fixed in #589. I'll do a release soon-ish. Gotta get some other stuff in.

**Comment by BerndWessels** [comment]
@timdorr @dsgkirkby Hi, this seems to be still broken.

Please see

https://github.com/reactjs/react-redux/issues/636

Thanks

**Comment by dsgkirkby** [comment]
I've updated the repro repo to 5.0.3 and the bug is still happening. Please reopen this ticket.
